---
- hosts: webserver
  gather_facts: False
  connection: local
  tasks:

    - name: Get python3
      apt: pkg=python3 state=present

    - name: Install pip
      become: true
      become_method: sudo
      become_user: root
      apt: name=python3-pip update_cache=yes state=latest
    - name: Install boto
      pip:
        name: boto      
    - name: Install boto3
      pip:
        name: boto3
  
    - name: EC2 Facts
      ec2_instance_facts:
        region: us-west-2
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: ec2

#    - name: Debug
#      debug:
#        msg: "{{ ec2 }}"
#    - name: Debugging
#      debug:
#        msg: "{{ ec2.instances[0].instance_id }}"

    - name: Kill EC2 Instance
      ec2:
        state: 'absent'
        region: us-west-2
        keypair: lukasz_sjsu
        instance_ids: "{{ ec2.instances[0].instance_id }}"
        wait: True
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
